// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVUeAe0aQGJyYw8csCnzbNKG5j2Iz6xlY',
    appId: '1:836220196127:web:3572e7d91e214606f74c2a',
    messagingSenderId: '836220196127',
    projectId: 'mahapro-c24bd',
    authDomain: 'mahapro-c24bd.firebaseapp.com',
    storageBucket: 'mahapro-c24bd.appspot.com',
    measurementId: 'G-D5FB6E0X4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbXPSEl5Q38zYlytGUKoPD8M-jnhmp_-w',
    appId: '1:836220196127:android:e72a121e9036d0d4f74c2a',
    messagingSenderId: '836220196127',
    projectId: 'mahapro-c24bd',
    storageBucket: 'mahapro-c24bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb1-MTdo7SL_j8st7_F14d6ZdW89F88CA',
    appId: '1:836220196127:ios:4dfaf529cabe7d57f74c2a',
    messagingSenderId: '836220196127',
    projectId: 'mahapro-c24bd',
    storageBucket: 'mahapro-c24bd.appspot.com',
    iosClientId: '836220196127-9m0ra2mrbbjhpd9541jiq069fniegnip.apps.googleusercontent.com',
    iosBundleId: 'com.studentpro.studentpro.studioProjects',
  );
}
